openapi: 3.0.1
info:
  title: API
  version: 1.0.0
  description: API description
  termsOfService: https://example.com/terms
  contact:
    name: API Support
    url: https://example.com/support
    email: robipolli@gmail.com
  license:
    name: MIT
    url: https://example.com/license
servers:
  - url: /api/v1
    description: API version 1
tags:
- name: EducationLevel
paths:
  /education-level:
    get:
      tags:
        - EducationLevel
      description: Get all education levels
      operationId: test_datapackage.list_entries
      parameters:
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: Offset the results
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of education levels
          content:
            text/turtle:
              schema:
                type: string
                format: bytes
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/EducationLevel'
            application/ld+json:
              schema:
                type: object
                properties:
                  "@context":
                    type: object
                  "@graph":
                    type: array
                    items:
                      type: object
        'default':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    EducationLevel:
      example: { "codice_1_livello": "FLA",
        "definizione": "Diploma conseguito con il nuovo ordinamento sui Corsi di Alta Formazione Artistica e Musicale (legge 508 del 1999 e successivo Decreto 212 del 2002). Questo Diploma \u00e8 conseguito al termine di un Corso di Alta Formazione artistica, musicale e coreutica di I livello di durata triennale, a cui si accede di norma con il diploma di scuola secondaria superiore o altro titolo di studio conseguito all\u2019estero, riconosciuto idoneo.",
        "label_ITA_1_livello": "Diploma accademico di Alta Formazione Artistica, Musicale e Coreutica di I livello",
        "label_ENG_1_livello": "Fine Arts, Drama, Dance and Music First level academic diploma (Bachelor's degree)"
      }
      type: object
      additionalProperties: false
      properties:
        codice_1_livello:
          type: string
        definizione:
          type: string
        label_ITA_1_livello:
          type: string
        label_ENG_1_livello:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
        status:
          type: string
        title:
          type: string
        type:
          type: string
        instance:
          type: string
        validation:
          type: object
          properties:
            keys:
              type: array
              items:
                type: string
            source:
              type: object
              properties:
                pointer:
                  type: string
                parameter:
                  type: string
                message:
                  type: string
                value:
                  type: string
                additional:
                  type: object
                  additionalProperties:
                    type: string
    Pagination:
      type: object
      properties:
        total:
          type: integer
          format: int32
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        count:
          type: integer
          format: int32
        links:
          type: object
          properties:
            first:
              type: string
            last:
              type: string
            next:
              type: string
            previous:
              type: string
            self:
              type: string
